# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/yumaly/workspace/project/ip_repo/zedboard_audio/constraints/zed_audio.xdc

# Block Designs: bd/lab4/lab4.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4 || ORIG_REF_NAME==lab4} -quiet] -quiet

# IP: bd/lab4/ip/lab4_processing_system7_0_0/lab4_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_processing_system7_0_0 || ORIG_REF_NAME==lab4_processing_system7_0_0} -quiet] -quiet

# IP: bd/lab4/ip/lab4_zed_audio_0_0/lab4_zed_audio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_zed_audio_0_0 || ORIG_REF_NAME==lab4_zed_audio_0_0} -quiet] -quiet

# IP: bd/lab4/ip/lab4_xlconstant_0_0/lab4_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_xlconstant_0_0 || ORIG_REF_NAME==lab4_xlconstant_0_0} -quiet] -quiet

# IP: bd/lab4/ip/lab4_FILTER_IIR_0_0/lab4_FILTER_IIR_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_FILTER_IIR_0_0 || ORIG_REF_NAME==lab4_FILTER_IIR_0_0} -quiet] -quiet

# IP: bd/lab4/ip/lab4_ps7_0_axi_periph_0/lab4_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_ps7_0_axi_periph_0 || ORIG_REF_NAME==lab4_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/lab4/ip/lab4_rst_ps7_0_100M_0/lab4_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_rst_ps7_0_100M_0 || ORIG_REF_NAME==lab4_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/lab4/ip/lab4_Volume_Pregain_0_0/lab4_Volume_Pregain_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_Volume_Pregain_0_0 || ORIG_REF_NAME==lab4_Volume_Pregain_0_0} -quiet] -quiet

# IP: bd/lab4/ip/lab4_xbar_0/lab4_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_xbar_0 || ORIG_REF_NAME==lab4_xbar_0} -quiet] -quiet

# IP: bd/lab4/ip/lab4_xlconcat_0_0/lab4_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_xlconcat_0_0 || ORIG_REF_NAME==lab4_xlconcat_0_0} -quiet] -quiet

# IP: bd/lab4/ip/lab4_axi_gpio_0_2/lab4_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_axi_gpio_0_2 || ORIG_REF_NAME==lab4_axi_gpio_0_2} -quiet] -quiet

# IP: bd/lab4/ip/lab4_AudioStream_0_0/lab4_AudioStream_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_AudioStream_0_0 || ORIG_REF_NAME==lab4_AudioStream_0_0} -quiet] -quiet

# IP: bd/lab4/ip/lab4_Volume_Pregain_0_1/lab4_Volume_Pregain_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_Volume_Pregain_0_1 || ORIG_REF_NAME==lab4_Volume_Pregain_0_1} -quiet] -quiet

# IP: bd/lab4/ip/lab4_FILTER_IIR_0_1/lab4_FILTER_IIR_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_FILTER_IIR_0_1 || ORIG_REF_NAME==lab4_FILTER_IIR_0_1} -quiet] -quiet

# IP: bd/lab4/ip/lab4_mixer_0_0/lab4_mixer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_mixer_0_0 || ORIG_REF_NAME==lab4_mixer_0_0} -quiet] -quiet

# IP: bd/lab4/ip/lab4_auto_pc_0/lab4_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab4_auto_pc_0 || ORIG_REF_NAME==lab4_auto_pc_0} -quiet] -quiet

# XDC: bd/lab4/lab4_ooc.xdc
