# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/yumaly/workspace/lab4/vivado/lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_gpio_0_2/lab4_axi_gpio_0_2.xci
# IP: The module: 'lab4_axi_gpio_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/yumaly/workspace/lab4/vivado/lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_gpio_0_2/lab4_axi_gpio_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab4_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/yumaly/workspace/lab4/vivado/lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_gpio_0_2/lab4_axi_gpio_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab4_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/yumaly/workspace/lab4/vivado/lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_gpio_0_2/lab4_axi_gpio_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab4_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/yumaly/workspace/lab4/vivado/lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_gpio_0_2/lab4_axi_gpio_0_2.xci
# IP: The module: 'lab4_axi_gpio_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/yumaly/workspace/lab4/vivado/lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_gpio_0_2/lab4_axi_gpio_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab4_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/yumaly/workspace/lab4/vivado/lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_gpio_0_2/lab4_axi_gpio_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab4_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/yumaly/workspace/lab4/vivado/lab4.srcs/sources_1/bd/lab4/ip/lab4_axi_gpio_0_2/lab4_axi_gpio_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab4_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
